import React from 'react';
import { AiReport } from '../types';

interface ReportViewProps {
  report: AiReport;
}

export const ReportView: React.FC<ReportViewProps> = ({ report }) => {
  return (
    <div className="bg-white rounded-lg shadow-lg border-t-4 border-primary p-8 mt-8 animate-fade-in print:shadow-none print:border-none print:mt-0">
      <div className="flex justify-between items-start mb-6 border-b pb-4">
        <div>
            <h2 className="text-2xl font-bold text-gray-800">Executive Performance Report</h2>
            <p className="text-sm text-gray-500 mt-1">Generated by Gemini AI • {report.generatedAt}</p>
        </div>
        <div className="text-right hidden print:block">
            <h3 className="text-xl font-bold text-primary">SheetReport Pro</h3>
        </div>
      </div>

      <div className="space-y-6">
        <section>
          <h3 className="text-lg font-semibold text-gray-700 mb-2 uppercase tracking-wide">Executive Summary</h3>
          <p className="text-gray-700 leading-relaxed text-justify">
            {report.summary}
          </p>
        </section>

        <section className="bg-blue-50 p-6 rounded-lg print:bg-transparent print:p-0">
          <h3 className="text-lg font-semibold text-blue-800 mb-3 uppercase tracking-wide">Key Insights</h3>
          <ul className="list-disc pl-5 space-y-2">
            {report.keyInsights.map((insight, idx) => (
              <li key={idx} className="text-gray-800">{insight}</li>
            ))}
          </ul>
        </section>

        <section className="border-l-4 border-green-500 pl-6 py-2 bg-green-50 print:bg-transparent">
          <h3 className="text-lg font-semibold text-green-800 mb-2 uppercase tracking-wide">Strategic Recommendation</h3>
          <p className="text-gray-800 font-medium italic">
            "{report.recommendation}"
          </p>
        </section>
      </div>

      <div className="mt-12 pt-8 border-t text-center text-xs text-gray-400 print:block hidden">
        <p>© {new Date().getFullYear()} SheetReport Pro. Confidential Document.</p>
      </div>
    </div>
  );
};